// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: urls.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countURLs = `-- name: CountURLs :one
SELECT COUNT(*) FROM urls
`

func (q *Queries) CountURLs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countURLs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createURL = `-- name: CreateURL :one
INSERT INTO urls (
    url, frequency, status, max_retries, timeout, rate_limit, 
    user_agent, parser_config, next_scrape_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, url, frequency, last_scraped_at, next_scrape_at, status, retry_count, max_retries, parser_config, user_agent, timeout, rate_limit, created_at, updated_at, deleted_at
`

type CreateURLParams struct {
	Url          string
	Frequency    string
	Status       string
	MaxRetries   int32
	Timeout      int32
	RateLimit    int32
	UserAgent    sql.NullString
	ParserConfig pqtype.NullRawMessage
	NextScrapeAt sql.NullTime
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.Url,
		arg.Frequency,
		arg.Status,
		arg.MaxRetries,
		arg.Timeout,
		arg.RateLimit,
		arg.UserAgent,
		arg.ParserConfig,
		arg.NextScrapeAt,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Frequency,
		&i.LastScrapedAt,
		&i.NextScrapeAt,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ParserConfig,
		&i.UserAgent,
		&i.Timeout,
		&i.RateLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getURLByID = `-- name: GetURLByID :one
SELECT id, url, frequency, last_scraped_at, next_scrape_at, status, retry_count, max_retries, parser_config, user_agent, timeout, rate_limit, created_at, updated_at, deleted_at FROM urls WHERE id = $1
`

func (q *Queries) GetURLByID(ctx context.Context, id uuid.UUID) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByID, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Frequency,
		&i.LastScrapedAt,
		&i.NextScrapeAt,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ParserConfig,
		&i.UserAgent,
		&i.Timeout,
		&i.RateLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listURLs = `-- name: ListURLs :many
SELECT id, url, frequency, last_scraped_at, next_scrape_at, status, retry_count, max_retries, parser_config, user_agent, timeout, rate_limit, created_at, updated_at, deleted_at FROM urls ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListURLsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListURLs(ctx context.Context, arg ListURLsParams) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Frequency,
			&i.LastScrapedAt,
			&i.NextScrapeAt,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ParserConfig,
			&i.UserAgent,
			&i.Timeout,
			&i.RateLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
