services:
  # Infrastructure Services
  postgres:
    image: postgres:15-alpine
    container_name: scraper-postgres
    environment:
      POSTGRES_DB: scraping_db
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema:/docker-entrypoint-initdb.d
    networks:
      - scraper-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: scraper-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - scraper-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: scraper-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - scraper-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: scraper-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - scraper-network

  # Application Services
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    container_name: scraper-api-gateway
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://scraper:scraper@postgres:5432/scraping_db?sslmode=disable
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - scraper-network
    restart: unless-stopped

  url-manager:
    build:
      context: .
      dockerfile: services/url-manager/Dockerfile
    container_name: scraper-url-manager
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://scraper:scraper@postgres:5432/scraping_db?sslmode=disable
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - scraper-network
    restart: unless-stopped

  # Monitoring Services
  prometheus:
    image: prom/prometheus:latest
    container_name: scraper-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - scraper-network

  grafana:
    image: grafana/grafana:latest
    container_name: scraper-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - scraper-network

volumes:
  postgres_data:
  grafana_data:

networks:
  scraper-network:
    driver: bridge 