// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Url struct {
	ID            uuid.UUID
	Url           string
	Frequency     string
	LastScrapedAt sql.NullTime
	NextScrapeAt  sql.NullTime
	Status        string
	RetryCount    int32
	MaxRetries    int32
	ParserConfig  pqtype.NullRawMessage
	UserAgent     sql.NullString
	Timeout       int32
	RateLimit     int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}
