// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Url struct {
	ID            uuid.UUID             `json:"id"`
	Url           string                `json:"url"`
	Frequency     string                `json:"frequency"`
	LastScrapedAt sql.NullTime          `json:"last_scraped_at"`
	NextScrapeAt  sql.NullTime          `json:"next_scrape_at"`
	Status        string                `json:"status"`
	RetryCount    int32                 `json:"retry_count"`
	MaxRetries    int32                 `json:"max_retries"`
	ParserConfig  pqtype.NullRawMessage `json:"parser_config"`
	UserAgent     sql.NullString        `json:"user_agent"`
	Timeout       int32                 `json:"timeout"`
	RateLimit     int32                 `json:"rate_limit"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	DeletedAt     sql.NullTime          `json:"deleted_at"`
}
