// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountURLs(ctx context.Context) (int64, error)
	CountURLsByStatus(ctx context.Context, status string) (int64, error)
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	GetURLByID(ctx context.Context, id uuid.UUID) (Url, error)
	GetURLsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Url, error)
	GetURLsByStatus(ctx context.Context, arg GetURLsByStatusParams) ([]Url, error)
	GetURLsForImmediateScraping(ctx context.Context, arg GetURLsForImmediateScrapingParams) ([]Url, error)
	GetURLsScheduledForScraping(ctx context.Context, arg GetURLsScheduledForScrapingParams) ([]Url, error)
	IncrementRetryCount(ctx context.Context, id uuid.UUID) error
	ListURLs(ctx context.Context, arg ListURLsParams) ([]Url, error)
	ResetRetryCount(ctx context.Context, id uuid.UUID) error
	UpdateLastScrapedTime(ctx context.Context, arg UpdateLastScrapedTimeParams) error
	UpdateNextScrapeTime(ctx context.Context, arg UpdateNextScrapeTimeParams) error
	UpdateURLStatus(ctx context.Context, arg UpdateURLStatusParams) error
}

var _ Querier = (*Queries)(nil)
