# API Gateway Configuration
# Settings specific to the API Gateway service

server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  cors:
    allowed_origins:
      - "*"
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed_headers:
      - Content-Type
      - Authorization
    max_age: 86400

# Inherit shared configurations
database:
  # Inherits from shared.yaml
  # Can override specific settings here if needed

kafka:
  # Inherits from shared.yaml
  # Can override specific settings here if needed

logging:
  # Inherits from shared.yaml
  # Can override specific settings here if needed
  level: info  # API Gateway specific log level

metrics:
  enabled: true
  port: 9090
  path: /metrics

# Health check settings
health:
  enabled: true
  path: /health
  readiness_path: /ready
  liveness_path: /live
  timeout: 5s

# Rate limiting
rate_limit:
  enabled: true
  requests_per_minute: 1000
  burst_size: 100 