server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  host: host.docker.internal
  port: 5432
  user: scraper
  password: scraper_password
  database: scraper
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m
  migration_path: ./migrations

kafka:
  brokers:
    - localhost:9092
  group_id: scraper-group
  auto_offset_reset: earliest
  enable_auto_commit: true
  auto_commit_interval: 1s
  session_timeout: 30s
  heartbeat_interval: 3s
  max_poll_records: 500
  max_poll_interval: 5m
  retry_backoff: 100ms
  retry_max_attempts: 3

scraping:
  default_timeout: 30s
  default_user_agent: "GoScraper/1.0 (https://github.com/your-repo/go-scraping-project)"
  default_rate_limit: 1
  max_retries: 3
  retry_delay: 5s
  html_storage_path: ./data/html
  max_concurrent_tasks: 10
  respect_robots_txt: true

logging:
  level: info
  format: json
  output: stdout
  include_caller: false

metrics:
  enabled: true
  port: 9090
  path: /metrics

tracing:
  enabled: false
  service_name: scraper-service
  jaeger_url: http://localhost:14268/api/traces 